experiment_numbers: 
    start: 112750
    end: 112750
    step: 1
# Experiment numbers defining list of experiments for summing tiff images.
    
file_paths:
    input_path: ../../SXRD_raw_data/diamond_2022_additional/rawdata/{experiment_number}-pilatus2M-files/
# Input path to the series of diffraction pattern tiff images
    
    output_path: ../../SXRD_analysis/diamond_2022_additional/texture-studies/{experiment_number}/
# Output path to save the summed/averaged diffraction pattern tiff image.

    background_scatter_path: None
# Path to tiff image recording the background.

    background_scatter_multiple: None
# Value to multiply the intensity values from the background image, to match the acquisition frequency of the experimental data.

grid_info:
    shape_x: 73
    shape_y: 51
# Total grid shape of individual diffraction pattern measurement points.    
    
    sample_numbers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
# Reference number for samples contained within the measurement grid.
    
    start_points:
      - [1,1]
      - [13,1]
      - [25,1]
      - [38,1]
      - [50,0]
      - [62,0]
      - [1,11]
      - [14,11]
      - [26,11]
      - [38,11]
      - [50,11]
      - [62,11]
      - [1,21]
      - [14,21]
      - [26,21]
      - [38,21]
      - [50,21]
      - [62,21]
      - [1,31]
      - [13,31]
      - [25,31]
      - [38,31]
      - [50,31]
      - [62,31]
      - [1,41]
      - [13,41]
      - [25,41]
      - [37,41]
      - [50,41]
      - [61,41]
# Start measurement point (X,Y) for each of the numbered samples.

    end_points:
      - [11,9]
      - [23,9]
      - [35,9]
      - [47,9]
      - [60,8]
      - [72,8]
      - [11,19]
      - [23,19]
      - [36,19]
      - [48,19]
      - [60,19]
      - [72,18]
      - [11,29]
      - [23,29]
      - [36,29]
      - [48,29]
      - [60,29]
      - [72,29]
      - [11,39]
      - [23,39]
      - [35,39]
      - [48,39]
      - [60,39]
      - [72,39]
      - [11,49]
      - [23,49]
      - [35,49]
      - [47,49]
      - [59,49]
      - [72,49]
# End measurement point (X,Y) for each of the numbered samples.