experiment_numbers: 
    start: 112748
    end: 112748
    step: 1
# Experiment numbers defining list of experiments for summing tiff images.
    
file_paths:
    input_path: ../../SXRD_raw_data/diamond_2022_additional/rawdata/{experiment_number}-pilatus2M-files/
# Input path to the series of diffraction pattern tiff images
    
    output_path: ../../SXRD_analysis/diamond_2022_additional/texture-studies/{experiment_number}/
# Output path to save the summed/averaged diffraction pattern tiff image.

    background_scatter_path: None
# Path to tiff image recording the background.

    background_scatter_multiple: None
# Value to multiply the intensity values from the background image, to match the acquisition frequency of the experimental data.

grid_info:
    shape_x: 72
    shape_y: 50
# Total grid shape of individual diffraction pattern measurement points.    
    
    sample_numbers: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
# Reference number for samples contained within the measurement grid.
    
    start_points:
      - [1,1]
      - [13,1]
      - [25,1]
      - [37,1]
      - [49,1]
      - [61,1]
      - [0,11]
      - [12,11]
      - [24,11]
      - [37,11]
      - [49,11]
      - [61,11]
      - [0,21]
      - [12,21]
      - [24,21]
      - [37,21]
      - [49,21]
      - [61,21]
      - [0,31]
      - [12,31]
      - [24,31]
      - [37,31]
      - [49,31]
      - [61,31]
      - [0,42]
      - [12,42]
      - [24,42]
      - [36,42]
      - [48,42]
      - [60,42]
# Start measurement point (X,Y) for each of the numbered samples.

    end_points:
      - [11,9]
      - [23,9]
      - [35,9]
      - [47,9]
      - [59,9]
      - [71,9]
      - [10,19]
      - [22,19]
      - [35,19]
      - [46,19]
      - [59,19]
      - [71,19]
      - [10,29]
      - [22,29]
      - [34,29]
      - [47,29]
      - [59,29]
      - [71,29]
      - [10,39]
      - [22,39]
      - [34,39]
      - [47,39]
      - [59,39]
      - [71,39]
      - [10,49]
      - [22,49]
      - [34,49]
      - [46,49]
      - [58,49]
      - [71,49]
# End measurement point (X,Y) for each of the numbered samples.